version: '3'
services:
  db:
    container_name: mundowap-test-cakephp-db
    image: mysql:8.0.34
    restart: always
    env_file:
      - .env.db
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql-db:/var/lib/mysql
  db_test:
    container_name: mysql_test
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
    ports:
      - "3307:3306"
    networks:
      - backend
    tmpfs: /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --max-connect-errors=1000 --connect-timeout=60
    restart: always
    depends_on:
      - db
  app:
    image: fmgusmao/php8-nginx
    container_name: mundowap-test-cakephp-app
    ports:
      - "13001:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./app:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.app
    depends_on:
      - db
    networks:
      - backend
volumes:
  mysql-db:
networks:
  backend:
    driver: bridge
